# Generated by Django 5.0.6 on 2024-08-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='detalle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
