# Generated by Django 5.0.6 on 2024-08-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_curso_detalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
