# Generated by Django 5.0.6 on 2024-08-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_entregable_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='detalle',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
